# main.yaml
# Lists of tasks to run within the mcp_server role.

---

- name: Install system packages
  ansible.builtin.apt:
    name:
        - python3
        - pipx
    state: present
    update_cache: true

- name: Create service user
  ansible.builtin.user:
    name: "{{ mcp_service_user }}"
    system: true
    create_home: true
    home: "/home/{{ mcp_service_user }}"
    shell: /usr/sbin/nologin # denies external SSH access

- name: Create filesystem on the data volume (i.e. EBS)
  community.general.filesystem:
    fstype: ext4
    dev: "{{ mcp_data_device }}"
  when: mcp_data_device | length > 0 # default is "" so 0

- name: Get volume UUID
  ansible.builtin.command: blkid -s UUID -o value {{ mcp_data_device }}
  register: mcp_vol_uuid
  changed_when: false
  when: mcp_data_device | length > 0 # default is "" so 0

- name: Mount the workspace volume
  ansible.posix.mount:
    path: "{{ mcp_workspace }}"
    src: "UUID={{ mcp_vol_uuid.stdout }}"
    fstype: ext4
    opts: "defaults,nofail"
    state: mounted
  when: mcp_data_device | length > 0 # default is "" so 0

- name: Own the workspace volume
  ansible.builtin.file:
    path: "{{ mcp_workspace }}"
    state: directory
    owner: "{{ mcp_service_user }}"
    group: "{{ mcp_service_user }}"
    mode: "2770"

- name: Let the admin user into the workspace
  ansible.builtin.user:
    name: "{{ mcp_admin_user }}"
    groups: "{{ mcp_service_user }}"
    append: true

- name: Install MCP server package via pipx
  ansible.builtin.command: pipx install mcp-server-remote
  environment:
    PIPX_HOME: "{{ pipx_home }}"
    PIPX_BIN_DIR: "{{ pipx_bin_dir }}"
  args:
    creates: "{{  pipx_bin_dir }}/mcp-server-remote"

- name: Create config dictionary
  ansible.builtin.file:
    path: "/home/{{ mcp_service_user }}/.config/mcp-server-remote"
    state: directory
    owner: "{{ mcp_service_user }}"
    mode: "0700"

- name: Configure server Config
  ansible.builtin.template:
    src: config.toml.j2
    dest: "/home/{{ mcp_service_user }}/.config/mcp-server-remote/config.toml"
    owner: "{{ mcp_service_user }}"
    mode: "0600"
  notify: Restart mcp-server-remote

- name: Install systemd unit
  ansible.builtin.template:
    src: mcp-server-remote.service.j2
    dest: /etc/systemd/system/mcp-server-remote.service
  notify: Restart mcp-server-remote

- name: Enable and start the service
  ansible.builtin.systemd_service:
    name: mcp-server-remote
    enabled: true
    state: started
    daemon_reload: true







